from . import res_users
from . import stock_location
from . import report_product_replenishment
from . import product_domain
from . import sale_order_line
from . import sale_order
from . import sale_report
from . import clone_access_rights
from . import forecast_wizard
from . import product_template